[package]
name = "neutralize"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = { version = "1.9", features = ["serde"] }
itertools = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
thiserror = "1.0"
